"""
GeneratedResponse model representing the final response generated by the OpenAI agent.
"""
from dataclasses import dataclass
from typing import List, Dict, Any, Optional
from datetime import datetime


@dataclass
class GeneratedResponse:
    """
    Represents the final response generated by the OpenAI agent.
    """
    id: str
    query_id: str
    text: str
    sources: List[Dict[str, Any]]
    grounding_confidence: float
    response_time_ms: int
    timestamp: datetime = None
    response_style: Optional[str] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()

    def validate(self) -> bool:
        """
        Validate the generated response parameters.
        """
        if not self.text or len(self.text.strip()) == 0:
            raise ValueError("Response text must not be empty")

        if not (0.0 <= self.grounding_confidence <= 1.0):
            raise ValueError("Grounding confidence must be between 0.0 and 1.0")

        if self.response_time_ms < 0:
            raise ValueError("Response time must be positive")

        if len(self.sources) > 10:
            raise ValueError("Sources array must not exceed 10 items")

        return True