openapi: 3.0.0
info:
  title: Chatbot API
  description: API for RAG chatbot functionality in the Physical AI Textbook platform
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /chat:
    post:
      summary: Chat with the RAG bot
      description: Send a message to the chatbot and receive a response based on Physical AI and robotics knowledge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response from the bot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /chat/health:
    get:
      summary: Health check for chatbot service
      description: Check if the chatbot service is running and healthy
      responses:
        '200':
          description: Chatbot service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Chatbot service is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 5000
          description: The user's message to the chatbot
          example: "Explain the basics of humanoid robotics control systems"
        sessionId:
          type: string
          description: Session identifier to maintain conversation context
          example: "session-uuid-123"
        userId:
          type: string
          description: User identifier (if authenticated)
          example: "user-uuid-456"
    ChatResponse:
      type: object
      required:
        - response
        - messageId
      properties:
        response:
          type: string
          description: The chatbot's response to the user's message
          example: "Humanoid robotics control systems typically involve..."
        messageId:
          type: string
          description: Unique identifier for this response
          example: "msg-uuid-789"
        sources:
          type: array
          description: List of sources used to generate the response
          items:
            type: string
          example: ["/docs/control-systems", "/docs/kinematics"]
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
          example: "2025-12-16T10:30:00Z"
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the service
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: When the health check was performed
          example: "2025-12-16T10:30:00Z"
        version:
          type: string
          description: Version of the chatbot service
          example: "1.0.0"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Service temporarily unavailable"
        code:
          type: string
          description: Error code
          example: "SERVICE_UNAVAILABLE"
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: "2025-12-16T10:30:00Z"